### ISSUE TITLE
卡在“plasma.tar.xz.7z.005已缓存 下载成功”不动

### ISSUE THREAD

**Issue by HikariQAQ** [kde-yyds/termux-x11-plasma-installer#11]
![Screenshot_20230807-180800](https://github.com/kde-yyds/termux-x11-plasma-installer/assets/122148875/c6eb843b-0f7c-4696-9797-b351478e1762)

**Comment by DieMoe233** [comment]
输入y，按回车

**Comment by HikariQAQ** [comment]
![Screenshot_20230808-105309.png](https://github.com/kde-yyds/termux-x11-plasma-installer/assets/122148875/775b9bcf-b252-4a71-b64d-e4a466367583)
