### ISSUE TITLE
一直等是吧

### ISSUE THREAD

**Issue by Darkzerofeather** [kde-yyds/termux-x11-plasma-installer#12]
![Screenshot_20230808_153242](https://github.com/kde-yyds/termux-x11-plasma-installer/assets/117582061/ca27ed04-2c27-4684-99e9-ce44a625a46a)

**Comment by kde-yyds** [comment]
6

**Comment by kde-yyds** [comment]
我懒得维护了，你自己下老版本吧（合并过一堆儿pr，确实有这问题了）

**Comment by Darkzerofeather** [comment]
> 
原来

**Comment by kde-yyds** [comment]
（手动🐔头

**Comment by Darkzerofeather** [comment]
> （手动🐔头

不（狗头）？

**Comment by kde-yyds** [comment]
addd，我是小黑子

**Comment by Darkzerofeather** [comment]
> addd，我是小黑子

老版本搁哪？（手动坤头）

**Comment by kde-yyds** [comment]
https://github.com/kde-yyds/termux-x11-plasma-installer/blob/7100d3da1c85d06414ae15b3b422aba7cf1c12bd/install.sh

**Comment by Darkzerofeather** [comment]
> https://github.com/kde-yyds/termux-x11-plasma-installer/blob/7100d3da1c85d06414ae15b3b422aba7cf1c12bd/install.sh

直接替换命令里的链接是吧（doge）

**Comment by kde-yyds** [comment]
打开链接 复制粘贴到一个文件里，加上运行权限，运行

**Comment by kde-yyds** [comment]
打开链接 复制粘贴到一个文件里，加上运行权限，运行

**Comment by Darkzerofeather** [comment]
> 打开链接 复制粘贴到一个文件里，加上运行权限，运行

好嘞

**Comment by dpkg123** [comment]
#11 

有没有一种可能，是文件正在解压中？
![Uploading Screenshot_2023-08-17-14-07-55-35_84d3000e3f4017145260f7618db1d683.jpg…]()

**Comment by dabao1955** [comment]
已解决，是我的锅(x
跟 #11 的错误是一样的
![Screenshot_2023-08-17-14-27-47-25_84d3000e3f4017145260f7618db1d683](https://github.com/kde-yyds/termux-x11-plasma-installer/assets/79307765/1d04a43c-7d2b-4de7-ac6a-602eedac96bd)
参见 #13
