### ISSUE TITLE
Can't start plasma after installation 

### ISSUE THREAD

**Issue by crazyraven** [kde-yyds/termux-x11-plasma-installer#14]
Hello,

Could you advise why plasma has not bee1n started?

-----------------------------------------
sha1sum: termux.tar.xz: No such file or directory
sha1sum: WARNING: 1 listed file could not be read
下载成功
sha1sum: plasma.tar.xz.7z.001: No such file or directory
sha1sum: WARNING: 1 listed file could not be read
下载成功
sha1sum: plasma.tar.xz.7z.002: No such file or directory
sha1sum: WARNING: 1 listed file could not be read
plasma.tar.xz.7z.002: OK
下载成功
sha1sum: plasma.tar.xz.7z.003: No such file or directory
sha1sum: WARNING: 1 listed file could not be read
plasma.tar.xz.7z.003: OK
下载成功
sha1sum: plasma.tar.xz.7z.004: No such file or directory
sha1sum: WARNING: 1 listed file could not be read
下载成功
sha1sum: plasma.tar.xz.7z.005: No such file or directory
sha1sum: WARNING: 1 listed file could not be read
下载成功
安装完毕，输入plasma并回车即可启动termux-x11+KDE Plasma
~ $ plasma
Loading shared library: /data/data/com.termux/files/usr/libexec/termux-x11/starter.apk!/lib/arm64-v8a/libx11-starter.so
$XDG_RUNTIME_DIR is unset.
Exporting default value (/data/data/com.termux/files/usr/tmp).
res = -92
Error: Activity class {com.termux.x11/com.termux.x11.TermuxX11StarterReceiver} does not exist.
Activity is not started
Unable to init server: 无法连接：拒绝连接
xfce4-panel: 无法打开显示：.
输入 “xfce4-panel --help” 获取用法。
mkdir: 无法创建目录 "/tmp/runtime-root": 文件已存在
I2023-09-08 02:01:42.965032 instance.cpp:1270] Override Enabled Addons: {}
I2023-09-08 02:01:42.965127 instance.cpp:1271] Override Disabled Addons: {}
I2023-09-08 02:01:43.061490 addonmanager.cpp:191] Loaded addon xcb
I2023-09-08 02:01:43.072597 addonmanager.cpp:191] Loaded addon quickphrase
I2023-09-08 02:01:43.073783 addonmanager.cpp:191] Loaded addon imselector
I2023-09-08 02:01:43.082447 addonmanager.cpp:191] Loaded addon keyboard
I2023-09-08 02:01:43.091011 addonmanager.cpp:191] Loaded addon dbus
I2023-09-08 02:01:43.132857 addonmanager.cpp:191] Loaded addon fcitx4frontend
I2023-09-08 02:01:43.142229 addonmanager.cpp:191] Loaded addon ibusfrontend
I2023-09-08 02:01:43.146852 addonmanager.cpp:191] Loaded addon xim
E2023-09-08 02:01:43.169348 waylandmodule.cpp:243] Failed to open wayland connection
I2023-09-08 02:01:43.169380 addonmanager.cpp:191] Loaded addon wayland
I2023-09-08 02:01:43.175112 addonmanager.cpp:191] Loaded addon dbusfrontend
I2023-09-08 02:01:43.177868 addonmanager.cpp:191] Loaded addon clipboard
I2023-09-08 02:01:43.180022 addonmanager.cpp:191] Loaded addon waylandim
I2023-09-08 02:01:43.181743 addonmanager.cpp:191] Loaded addon unicode
I2023-09-08 02:01:43.190192 addonmanager.cpp:191] Loaded addon pinyinhelper
I2023-09-08 02:01:43.254513 inputmethodmanager.cpp:198] Found 723 input method(s) in addon keyboard
I2023-09-08 02:01:43.259288 addonmanager.cpp:191] Loaded addon kimpanel
I2023-09-08 02:01:43.347328 addonmanager.cpp:191] Loaded addon classicui
I2023-09-08 02:01:43.354128 addonmanager.cpp:191] Loaded addon notificationitem
I2023-09-08 02:01:43.358794 addonmanager.cpp:191] Loaded addon notifications
I2023-09-08 02:01:43.359171 kimpanel.cpp:112] Kimpanel new owner:
Android reported activity started but we did not get any respond
Looks like we failed to start activity.
$DISPLAY is not set or cannot connect to the X server.
-----------------------------------------

termux-x11 didn't start as well please help

Thank you for your great script!!

Best regards

**Comment by kde-yyds** [comment]
自己更新termux x11

**Comment by kde-yyds** [comment]
https://github.com/termux/termux-x11/
please install the latest version of termux-x11 there. the binary from this script is very old and unstable
