### ISSUE TITLE
遇到点問题

### ISSUE THREAD

**Issue by 2376780283** [kde-yyds/termux-x11-plasma-installer#16]
挂VPN可以正常下载install.sh 
储存权限都给了 网络也正常 （vpn） 
termux.tar.xz: FAILED open or read
log↓
~ $ chmod +x install.sh
~ $ ./install.sh
Hit:1 https://mirrors.bfsu.edu.cn/termux/apt/termux-main stable InRelease
Hit:2 https://mirrors.bfsu.edu.cn/termux/apt/termux-x11 x11 InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

sha1sum: termux.tar.xz: No such file or directory
sha1sum: WARNING: 1 listed file could not be read
sha1sum: termux.tar.xz: No such file or directory
sha1sum: WARNING: 1 listed file could not be read
下载失败，即将退出，请检查log.txt的输出信息

**Comment by kde-yyds** [comment]
不挂梯子应该可以吧

**Comment by 2376780283** [comment]
确实是这样 必须要挂梯子

**Comment by 2376780283** [comment]
termux.tar.xz: FAILED open or read
没有root跑不了吗

**Comment by kde-yyds** [comment]
> termux.tar.xz: FAILED open or read
> 没有root跑不了吗

不用root

**Comment by lgffllsxx** [comment]
`Hit:1 http://ports.ubuntu.com/ubuntu-ports mantic InRelease
Hit:2 http://ports.ubuntu.com/ubuntu-ports mantic-updates InRelease
Hit:3 http://ports.ubuntu.com/ubuntu-ports mantic-security InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

sha1sum: termux.tar.xz: No such file or directory
sha1sum: WARNING: 1 listed file could not be read
sha1sum: termux.tar.xz: No such file or directory
sha1sum: WARNING: 1 listed file could not be read
下载失败，即将退出，请检查log.txt的输出信息`
我也遇到了这个问题，设备是matepad air，网络也正常，梯子挂不挂都试了，权限也都给了，我感觉可能是termux.tar.xz的问题，我尝试用浏览器访问install.sh中的链接，但是打不开。

**Comment by kde-yyds** [comment]
再试试，应该行了吧
