### ISSUE TITLE
为什么桌面下方的panel是一个xfce4-panel，而且没有办法移除

### ISSUE THREAD

**Issue by lifeformg** [kde-yyds/termux-x11-plasma-installer#17]
![image](https://github.com/kde-yyds/termux-x11-plasma-installer/assets/46708704/27acc306-2787-49bc-a38b-488b83d23781)
这个地方的panel我想换成plasma的默认面板，但是我没有找到能移除这个panel的方法。直接添加一个plasma默认面板的话，plasma的任务栏没办法用，最小化后的程序还是在这个移除不掉的xfce4-panel里面。我用kde很长时间了，但是我不懂为什么kde里面会存在一个xfce4-panel。有办法移除掉它吗？

**Comment by kde-yyds** [comment]
当时我搞的这个方案是另开一个debian11容器跑kwin xrender和xfce panel（kwin和kde如果不是在同一个容器kde的面板获取不了窗口列表）

**Comment by kde-yyds** [comment]
如果要跑kwin xrender这也许是更好的方案
把debian11点rootfs拷到arch的/usr/share/debian11-kwin
然后执行这个脚本
```
#!/bin/bash
export QT_PLUGIN_PATH=/usr/share/debian11-kwin/lib/aarch64-linux-gnu/qt5/plugins/
export LD_LIBRARY_PATH=/usr/share/debian11-kwin/lib/:/usr/share/debian11-kwin/lib/aarch64-linux-gnu/:/usr/share/debian11-kwin/lib/aarch64-linux-gnu/pulseaudio/
#export LD_PRELOAD=/usr/share/debian11-kwin/lib/aarch-linux-gnu/libc.so.6
set -e KWIN_COMPOSE
/usr/share/debian11-kwin/lib/ld-linux-aarch64.so.1 /usr/share/debian11-kwin/bin/kwin --replace
```

**Comment by kde-yyds** [comment]
如果你有root能跑chroot且是高通的处理器的话可以考虑用turnip zink跑kwin wayland（跑x11的有点小问题，窗口内容是空的）然后编译带termux x11点dri3的Xwayland替换系统带的，然后在Xwayland里跑plasma x11

效果最好，但比kwin xrender的方案更卡一些
kde-yyds刚刚发布的视频https://b23.tv/24kU8a9

**Comment by lifeformg** [comment]
感谢回复
