### ISSUE TITLE
硬件加速

### ISSUE THREAD

**Issue by strayedstar** [kde-yyds/termux-x11-plasma-installer#2]
没有对于视频，3d等等还是不行。
试试适配zink渲染器，Vulkan后端。
现在有一个mesa的xorg包，mtk和sdm系列的soc都支持Vulkan转opengl

**Comment by kde-yyds** [comment]
我试过zink,我那脚本安装的termux prefix就自带zink和virgl render
安卓缺很多vulkan扩展（安卓的vk library里就缺）
在这种情况下，zink就变成了软件渲染，性能提升不了多少，而且会使一些gl程序不稳定甚至崩溃，zink软件渲染的图像质量也不好
再说，即使你的安卓完全支持vulkan，zink也不适合或者不非常合适日常使用
我的电脑 intel核显完全支持vulkan（也不是完全，但至少能开硬件加速的zink）
性能损耗感受不到，和直接渲染opengl差不多
但是
chromium的颜色不正常，十分阴间
qtquick3d也不能正常运行

总之我不会默认启用zink

还有一个能获取真正的安卓硬件加速的方法是链接安卓的egl library
然后用gl4es
能获取真正的硬件加速
glxgears 3万帧
不过那egl不支持输出到x11,所以能渲染但无法输出画面
可惜用virgl也会崩

所以还是好好用xrender软件渲染吧
反正也不卡

**Comment by kde-yyds** [comment]
Is it possible to make virglrender work with android's libEGL libGLES and without mesa libgbm? @twaik
