### ISSUE TITLE
华为手机/平板卡得不能用

### ISSUE THREAD

**Issue by Fernand0r** [kde-yyds/termux-x11-plasma-installer#3]
华为的2K分辨率平板卡的动不了，系统设置又改不了分辨率，在Linux桌面下xrandr配置了720P的分辨率也没生效，重启一下显示设置里面的720P选项都没了。

**Comment by kde-yyds** [comment]
termux-x11暂时不支持自定义分辨率，不过有人提过issue了，以后termux-x11应该会实现

**Comment by kde-yyds** [comment]
但是华为不是能调分辨率的吗？设置里

**Comment by Fernand0r** [comment]
> 

是的，鸿蒙平板调不了分辨率，只有一个智能分辨率开启选项😂

**Comment by kde-yyds** [comment]
对了
我知道了
（我用的也是华为
华为会给termux降频
所以
开adb
连电脑
adb shell pm uninstall --user 0 com.huawei.powergenie
解决

**Comment by Fernand0r** [comment]
> 对了 我知道了 （我用的也是华为 华为会给termux降频 所以 开adb 连电脑 adb shell pm uninstall --user 0 com.huawei.powergenie 解决

thx~ 把这个进程冻结后，虽然还是有点卡，但没有卡死了。

**Comment by kde-yyds** [comment]
那我把issue关喽
