### ISSUE TITLE
Change language

### ISSUE THREAD

**Issue by drakulaboy** [kde-yyds/termux-x11-plasma-installer#6]
Hi, i'm a newbie in Plasma KDE, but i love the GUI, how do i change the language fully in the Plasma KDE, i added English in Plasma KDE settings, but half of interface is still in Chinese, i even changed the "zh_CN" with "en_US" in the file "/data/data/com.termux/files/home/containers/scripts/archlinuxarm_plasma.sh"
and "/data/data/com.termux/files/home/containers/scripts/debianbullseye_xrenderkwin_xfce4-panel.sh"

**Comment by dabao1955** [comment]
Hello, may I ask if you mentioned changing the language in Debian Linux? If so, try `sudo dpkg configure locales`or add `export LANG=en_US.UTF-8` in `.bashrc`.

**Comment by kde-yyds** [comment]
> 

Can you provide a screenshot?

**Comment by drakulaboy** [comment]
i changed from the Language settings to be English but language of apps and some parts of OS are still in cn

**Comment by drakulaboy** [comment]
![Screenshot_20230419_154320_com termux x11](https://user-images.githubusercontent.com/7822898/233079602-569485f4-f38b-48c5-bb02-2be009391a93.jpg)
![Screenshot_20230419_154213_com termux x11](https://user-images.githubusercontent.com/7822898/233079604-7459f4f2-247d-499f-8962-216825025e83.jpg)
![Screenshot_20230419_154204_com termux x11](https://user-images.githubusercontent.com/7822898/233079607-1065d60c-9824-4aa3-b0c8-e47dd6d6c1a4.jpg)
![Screenshot_20230419_154138_com termux x11](https://user-images.githubusercontent.com/7822898/233079609-4e38f200-ef17-44a2-9d72-7dc6a126bff9.jpg)
![Screenshot_20230419_154151_com termux x11](https://user-images.githubusercontent.com/7822898/233079611-4a687a55-06e4-4544-bd38-386775898674.jpg)

**Comment by kde-yyds** [comment]
Can ypu provide output of  ```env```

**Comment by drakulaboy** [comment]
![Screenshot_20230422_210833_com termux x11](https://user-images.githubusercontent.com/7822898/233799983-30fcedf9-a22b-4ed1-a23c-927c86f85a60.jpg)

**Comment by kde-yyds** [comment]
well, LANG is still zh_CN.UTF8

**Comment by drakulaboy** [comment]
how to change it completely? or needs another version of distribution?

**Comment by kde-yyds** [comment]
just edit the script
![Screenshot_20230425_231704_com termux](https://user-images.githubusercontent.com/106876912/234323864-d4a95e18-dcc0-4246-8ea7-136039e27737.jpg)

**Comment by drakulaboy** [comment]
great, thank you, i will try
