### ISSUE TITLE
无法下载install.sh

### ISSUE THREAD

**Issue by JasonZ-Star** [kde-yyds/termux-x11-plasma-installer#7]
使用readme中的链接无法下载install.sh，尝试更改为https://raw.githubusercontent.com/kde-yyds/termux-x11-plasma-installer/master/install.sh后可以下载，建议作者更新一下

**Comment by dabao1955** [comment]
![Screenshot_2023-05-06-22-33-16-499_com termux](https://user-images.githubusercontent.com/79307765/236630563-d822179b-ae22-4597-8479-4321242feaa8.jpg)
Please check your network.
