### ISSUE TITLE
启动x11报错

### ISSUE THREAD

**Issue by lanping666** [kde-yyds/termux-x11-plasma-installer#9]
如题，启动x11报错
终端显示:Loading shared library: /data/data/com.termux/files/usr/libexec/termux-x11/starter.apk!/lib/arm64-v8a/libx11-starter.so
$XDG_RUNTIME_DIR is unset.
Exporting default value (/data/data/com.termux/files/usr/tmp).
java.lang.IllegalAccessException: Class java.lang.Class<com.termux.x11.starter.Compat> cannot access  method void android.app.AppOpsManager.<init>(android.content.Context, com.android.internal.app.IAppOpsService) of class java.lang.Class<android.app.AppOpsManager>
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
        at com.termux.x11.starter.Compat.havePermission(Compat.java:56)
        at com.termux.x11.starter.Starter.onRun(Starter.java:66)
        at com.termux.x11.starter.Starter.lambda$main$0(Starter.java:42)
        at com.termux.x11.starter.Starter$$ExternalSyntheticLambda2.run(D8$$SyntheticClass)
        at java.lang.Thread.run(Thread.java:776)
Looks like com.termux lacks "Draw Over Apps" permission.
You can grant com.termux the "Draw Over Apps" permission from its App Info activity:
        Android Settings -> Apps -> Termux -> Advanced -> Draw over other apps.
/data/data/com.termux/files/usr/bin/plasma: line 7: /data/data/com.termux/files/home/containers/scripts/debianbullseye_xrenderkwin_xfce4-panel.sh: No such file or directory
/data/data/com.termux/files/usr/bin/plasma: line 8: /data/data/com.termux/files/home/containers/scripts/archlinuxarm_plasma.sh: No such file or directory
~ $ res = 0
Activity is started
Got getWaylandFD
{ParcelFileDescriptor: java.io.FileDescriptor@8de75d1}
Lorie requested fd
Got getLogFD
{ParcelFileDescriptor: java.io.FileDescriptor@f440836}
Got finish request
App sent finishing command
Starting Xwayland
missing XDG-WM-Base protocol
(EE)
Fatal server error:
(EE) Couldn't add screen
(EE)
![Uploading Screenshot_20230603-055026.png…]()

通知中的报错:## Report Info

**User Action**: `plugin execution command`  
**Sender**: `RunCommandService`  
**Report Timestamp**: `2023-06-02 21:49:29.589 UTC`  
##

## RUN_COMMAND Execution Intent Command

**Previous State**: `Pre-Execution`  
**Current State**: `Failed`  
**Executable**: `/data/data/com.termux/files/usr/libexec/termux-x11/termux-startx11`  
**Arguments:** -  
**Working Directory**: -  
**inBackground**: `true`  
**isFailsafe**: `false`  
**Session Action**: -  
**isPluginExecutionCommand**: `true`  

**Result PendingIntent Creator:** -  

**Stdout**: -  
**Stderr**: -  
**Exit Code**: -  

**Error Code**: `2`  
**Error Message**:
````
RunCommandService requires `allow-external-apps` property to be set to `true` in `~/.termux/termux.properties` file.
````

### StackTraces

`-`
##

### Plugin API Help

Visit https://github.com/termux/termux-app/wiki/RUN_COMMAND-Intent for more info on RUN_COMMAND Intent usage.
##

## Termux App Info

**APP_NAME**: `Termux`  
**PACKAGE_NAME**: `com.termux`  
**VERSION_NAME**: `0.118.0`  
**VERSION_CODE**: `118`  
**TARGET_SDK**: `28`  
**IS_DEBUGGABLE_BUILD**: `true`  
**APK_RELEASE**: `Github`  
**SIGNING_CERTIFICATE_SHA256_DIGEST**: `B6DA01480EEFD5FBF2CD3771B8D1021EC791304BDD6C4BF41D3FAABAD48EE5E1`  
##

### Software

**OS_VERSION**: `3.18.31-perf-g7b01bd5`  
**SDK_INT**: `24`  
**RELEASE**: `7.0`  
**ID**: `HUAWEICAZ-AL10`  
**DISPLAY**: `CAZ-AL10C00B387`  
**INCREMENTAL**: `C00B387`  
**SECURITY_PATCH**: `2018-12-01`  
**IS_DEBUGGABLE**: `0`  
**TYPE**: `user`  
**TAGS**: `release-keys`  

### Hardware

**MANUFACTURER**: `HUAWEI`  
**BRAND**: `HUAWEI`  
**MODEL**: `HUAWEI CAZ-AL10`  
**PRODUCT**: `CAZ-AL10`  
**BOARD**: `CAZ-AL10`  
**HARDWARE**: `qcom`  
**DEVICE**: `HWCAZ`  
**SUPPORTED_ABIS**: `arm64-v8a, armeabi-v7a, armeabi`  
##
![Uploading Screenshot_2023-06-03-05-49-49.jpg…]()

**Comment by kde-yyds** [comment]
那是termux-x11的问题，你自己去下载最新的吧，虽然最新的很卡

**Comment by kde-yyds** [comment]
@lanping666 更新最新的吧，性能问题修复了，体验很好
